//To change html code to javascript string
//LINK:http://www.accessify.com/tools-and-wizards/developer-tools/html-javascript-convertor/

var navBarCode="";
navBarCode += "<div class=\"container-fluid col-xs-12\">";
navBarCode += "			<!--Navigation logo-->";
navBarCode += "			<div class=\"navbar-header col-xs-2\">";
navBarCode += "";
navBarCode += "				<a class=\"navbar-brand\" href=\"#\">";
navBarCode += "					<span class=\"glyphicon glyphicon-star\"><\/span><\/p>";
navBarCode += "				<\/a>";
navBarCode += "";
navBarCode += "			<\/div>";
navBarCode += "";
navBarCode += "";
navBarCode += "			<!-- Navigation Search-->";
navBarCode += "";
navBarCode += "			<div class=\"col-xs-6\" >";
navBarCode += "				<form role=\"search\">";
navBarCode += "					<div class=\"col-xs-1\">";
navBarCode += "						<ul class=\"nav navbar-nav\">";
navBarCode += "							<li class=\"dropdown\">";
navBarCode += "								<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">";
navBarCode += "									<span class=\"glyphicon glyphicon-menu-hamburger\" aria-hidden=\"true\"><\/span>";
navBarCode += "								<\/a>";
navBarCode += "								<ul class=\"dropdown-menu\">";
navBarCode += "									<li><a href=\"#\"> Page 1-1 <\/a><\/li>";
navBarCode += "									<li>	<a href=\"#\"> Page 1-2 <\/a><\/li>";
navBarCode += "									<li><a href=\"#\"> Page 1-3 <\/a><\/li>";
navBarCode += "								<\/ul>";
navBarCode += "							<\/li>";
navBarCode += "						<\/ul>";
navBarCode += "					<\/div>";
navBarCode += "					<div class=\"col-xs-10\" id=\"searchBoxMP\">";
navBarCode += "						<input type=\"text\" class=\"form-control\" placeholder=\"Search\" >";
navBarCode += "					<\/div>";
navBarCode += "					<div class=\"col-xs-1\"   id=\"btnSubmitMP\">";
navBarCode += "						<button type=\"submit\" class=\"btn btn-default\">";
navBarCode += "							<span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"><\/span>";
navBarCode += "						<\/button>";
navBarCode += "					<\/div>";
navBarCode += "				<\/form>";
navBarCode += "			<\/div>";
navBarCode += "";
navBarCode += "			<!-- Navigation Login-->";
navBarCode += "			<div class=\"col-xs-4\">";
navBarCode += "             <div class=\"col-xs-4\">";
navBarCode += "            		 <a class=\"btn btn-primary btn-lg\" align=\"center\" href=\"signup.php\">Daftar</a>";
navBarCode += "             </div>"
navBarCode += "				<div class=\"col-xs-4\">";
navBarCode += "					<!-- The drop down menu -->";
navBarCode += "					<ul class=\"nav navbar-nav pull-right\">";
navBarCode += "";
navBarCode += "						<li class=\"dropdown\">";
navBarCode += "							<a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">Masuk <strong class=\"caret\"><\/strong><\/a>";
navBarCode += "							<div class=\"dropdown-menu\" style=\"padding: 15px; padding-bottom: 0px;\">";
navBarCode += "								<!-- Login form here -->";
navBarCode += "								<form action=\"\/startUp\/login.php\" method=\"post\" accept-charset=\"UTF-8\">";
navBarCode += "									<input id=\"user_username\" style=\"margin-bottom: 15px;\" type=\"text\" name=\"email\" size=\"30\" placeholder=\"Email\"\/>";
navBarCode += "									<input id=\"user_password\" style=\"margin-bottom: 15px;\" type=\"password\" name=\"password\" size=\"30\" placeholder=\"Password\"\/>";
navBarCode += "                                 <div class=\"form-group\">";
navBarCode += "									<input id=\"user_remember_me\" style=\"float: left; margin-right: 10px;\" type=\"checkbox\" name=\"user[remember_me]\" value=\"1\" \/>";
navBarCode += "									<label class=\"string optional\" for=\"user_remember_me\"> Remember me<\/label>";
navBarCode += "                                    <a style=\"float:right\" href=\"sign_up.php\">Daftar</a>";
navBarCode += "                                 <\/div>";
navBarCode += "									<input class=\"btn btn-primary\" style=\"clear: left; width: 100%; height: 32px; font-size: 13px;\" type=\"submit\" name=\"commit\" value=\"Sign In\" \/>";
navBarCode += "								<\/form>";
navBarCode += "							<\/div>";
navBarCode += "						<\/li>";
navBarCode += "					<\/ul>";
navBarCode += "					<!--<a class=\"navbar-brand navbar-collapse full\" id=\"loginDropdown\" href=\"#\">Masuk<\/a>-->";
navBarCode += "				<\/div>";
navBarCode += "";
navBarCode += "				<div class=\"col-xs-4\">";
navBarCode += "					<ul class=\"nav navbar-nav\">";
navBarCode += "						<li class=\"dropdown\">";
navBarCode += "							<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">";
navBarCode += "								<span class=\"glyphicon glyphicon-globe\" aria-hidden=\"true\"><\/span>";
navBarCode += "							<\/a>";
navBarCode += "							<ul class=\"dropdown-menu\">";
navBarCode += "								<li><a href=\"#\"> Indonesia <\/a><\/li>";
navBarCode += "";
navBarCode += "							<\/ul>";
navBarCode += "						<\/li>";
navBarCode += "					<\/ul>";
navBarCode += "				<\/div>";
navBarCode += "			<\/div>";
navBarCode += "		<\/div>";

document.getElementById("navBar").innerHTML = navBarCode;


/**Login in navigation jquery**/
