var navbarAftLogin="";
navbarAftLogin += "<!--Navigation logo-->			";
navbarAftLogin += "		<div class=\"navbar-header col-xs-2\">";
navbarAftLogin += "			<a class=\"navbar-brand\" href=\"#\">		<span class=\"glyphicon glyphicon-star\"><\/span>";
navbarAftLogin += "				<p><\/p>	";
navbarAftLogin += "			<\/a>			";
navbarAftLogin += "		<\/div>			<!-- Navigation Search-->			";
navbarAftLogin += "		<div class=\"col-xs-6\">";
navbarAftLogin += "			<form role=\"search\">					";
navbarAftLogin += "				<div class=\"col-xs-1\">	";
navbarAftLogin += "					<ul class=\"nav navbar-nav\">";
navbarAftLogin += "						<li class=\"dropdown\">";
navbarAftLogin += "							<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">";
navbarAftLogin += "								<span class=\"glyphicon glyphicon-menu-hamburger\" aria-hidden=\"true\"><\/span>	";
navbarAftLogin += "							<\/a>							";
navbarAftLogin += "							<ul class=\"dropdown-menu\">		";
navbarAftLogin += "								<li><a href=\"#\"> Page 1-1 <\/a><\/li>		";
navbarAftLogin += "								<li>	<a href=\"#\"> Page 1-2 <\/a><\/li>		";
navbarAftLogin += "								<li><a href=\"#\"> Page 1-3 <\/a><\/li>		";
navbarAftLogin += "							<\/ul>						";
navbarAftLogin += "						<\/li>					";
navbarAftLogin += "					<\/ul>				";
navbarAftLogin += "				<\/div>			";
navbarAftLogin += "				<div class=\"col-xs-10\" id=\"searchBoxMP\">	";
navbarAftLogin += "					<input type=\"text\" class=\"form-control\" placeholder=\"Search\">	";
navbarAftLogin += "				<\/div>				";
navbarAftLogin += "				<div class=\"col-xs-1\" id=\"btnSubmitMP\">	";
navbarAftLogin += "					<button type=\"submit\" class=\"btn btn-default\">		";
navbarAftLogin += "						<span class=\"glyphicon glyphicon-search\" aria-hidden=\"true\"><\/span>						<\/button>	";
navbarAftLogin += "					<\/div>		";
navbarAftLogin += "				<\/form>	";
navbarAftLogin += "			<\/div>			";
navbarAftLogin += "			<!-- Search bar after login-->";
navbarAftLogin += "			<div class=\"col-xs-4\">";
navbarAftLogin += "";
navbarAftLogin += "				<!--Notification-->";
navbarAftLogin += "				<div class=\"col-xs-2\">	";
navbarAftLogin += "					<ul class=\"nav navbar-nav\" align=\"center\">		";
navbarAftLogin += "						<li class=\"dropdown\">					";
navbarAftLogin += "							<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">			";
navbarAftLogin += "								<span class=\"glyphicon glyphicon-th\" aria-hidden=\"true\"><\/span>							";
navbarAftLogin += "							<\/a>	";
navbarAftLogin += "							<!-- Retrieve data-->";
navbarAftLogin += "							<!--<?php?>-->";
navbarAftLogin += "						<\/li>";
navbarAftLogin += "					<\/ul>		";
navbarAftLogin += "				<\/div>	";
navbarAftLogin += "";
navbarAftLogin += "				<!--Create Thread-->";
navbarAftLogin += "				<div class=\"col-xs-6\" 	>	";
navbarAftLogin += "					<a  style=\"width:100%\"class=\"btn btn-primary btn-lg\" type=\"button\" href=\"create-thread.html\" >Create Thread<\/a>				";
navbarAftLogin += "				<\/div>		";
navbarAftLogin += "";
navbarAftLogin += "				<!--Other-->";
navbarAftLogin += "				<div class=\"col-xs-2\">";
navbarAftLogin += "					<ul class=\"nav navbar-nav\">";
navbarAftLogin += "						<li class=\"dropdown\">";
navbarAftLogin += "							<a class=\"dropdown-toggle\" data-toggle=\"dropdown\">";
navbarAftLogin += "								<span class=\"glyphicon glyphicon-menu-down\" aria-hidden=\"true\"><\/span>";
navbarAftLogin += "							<\/a>";
navbarAftLogin += "							<ul class=\"dropdown-menu\">";
navbarAftLogin += "								<li> <a href=\"php\/logout.php\">Logout<\/a><\/li>";
navbarAftLogin += "							<\/ul>";
navbarAftLogin += "						<\/li>";
navbarAftLogin += "					<\/ul>";
navbarAftLogin += "				<\/div>";
navbarAftLogin += "";
navbarAftLogin += "				<!--Forum Country-->";
navbarAftLogin += "				<div class=\"col-xs-2\">";
navbarAftLogin += "					<ul class=\"nav navbar-nav\">";
navbarAftLogin += "						<li class=\"dropdown\">";
navbarAftLogin += "							<a class=\"dropdown-toggle\" data-toggle=\"dropdown\">";
navbarAftLogin += "								<span class=\"glyphicon glyphicon-globe\" aria-hidden=\"true\"><\/span>";
navbarAftLogin += "							<\/a>";
navbarAftLogin += "							<ul class=\"dropdown-menu\">";
navbarAftLogin += "								<li> <a>Indonesia<\/a><\/li>";
navbarAftLogin += "							<\/ul>";
navbarAftLogin += "						<\/li>";
navbarAftLogin += "					<\/ul>";
navbarAftLogin += "				<\/div>";
navbarAftLogin += "";
navbarAftLogin += "			<\/div>";



document.getElementById("navbarAfterLogin").innerHTML = navbarAftLogin;
