var navSideCode="";

navSideCode += "";
navSideCode += "				<ul class=\"nav nav-sidebar\">";
navSideCode += "";
navSideCode += "";
navSideCode += "					<li class=\"dropdown\">";
navSideCode += "";
navSideCode += "						<a class=\"dropdown-toggle\" href=\"#\" data-toggle=\"dropdown\">";
navSideCode += "							DEBAT ";
navSideCode += "							<strong class=\"caret\"><\/strong>";
navSideCode += "						<\/a>";
navSideCode += "						";
navSideCode += "						<!--DEBATE SUB-->";
navSideCode += "						<ul class=\"dropdown-menu\">";
navSideCode += "							<li><a href=\"#\"> Popular <\/a><\/li>";
navSideCode += "							<li><a href=\"#\"> New <\/a><\/li>";
navSideCode += "";
navSideCode += "						<\/ul>";
navSideCode += "";
navSideCode += "						";
navSideCode += "";
navSideCode += "";
navSideCode += "					<\/li>";
navSideCode += "					";
navSideCode += "";
navSideCode += "";
navSideCode += "					<li >";
navSideCode += "						<a href=\"#\">";
navSideCode += "							PERTANYAAN";
navSideCode += "						<\/a>";
navSideCode += "					<\/li>	";
navSideCode += "";
navSideCode += "					<li>";
navSideCode += "						<a href=\"#\">";
navSideCode += "							PETISI";
navSideCode += "						<\/a>";
navSideCode += "					<\/li>";
navSideCode += "				<\/ul>";

document.getElementById("navSide").innerHTML = navSideCode;
